### ISSUE TITLE
hisat2 command missing un-paired reads

### ISSUE THREAD

**Issue by spficklin** [feltus/OSG-GEM#10]
I noticed that in the tools/hisat2 file that when hisat2 is executed it does not include the -U command that includes the unpaired reads that were placed in a separate file after trimmomatic.  

Just curious if those were meant to be included and accidentally left out?

**Comment by wpoehlm** [comment]
I usually only process paired end data, but  I was using -U to signify Single end read(unpaired) input files.  For paired-end reads, I would think that we only want to align reads that form proper pairs following trimming.  Does that make sense or should I consider mapping unpaired reads too?

**Comment by spficklin** [comment]
My thinking is... why waste the reads if they are there even if they are unpaired.  If they map then they indicate gene expression.  Mapping them (or not mapping them) will affect the counts, and it will do so disproportionately for lower expressed genes. Although I suppose they won't map as accurately as paired-reads may map which may be problematic. But I wonder if its worth adding unpaired reads to the alignment to help improve the resolution of those lower expressed genes? I may be wrong, it's just my gut feeling.

**Comment by wpoehlm** [comment]
I definitely see what you're saying.  In the end we're looking for relative transcript abundances, so wouldn't increasing the total number of mapped reads (theoretically) result in a comparable FPKM value?  This is of course assuming we have sufficient sequencing depth from the paired reads.   My worry with adding the unpaired reads is that they won't map accurately compared to the paired reads, as you mentioned, which could skew the FPKM values

**Comment by wpoehlm** [comment]
I'm still not completely decided on this, but I am going to stick with throwing out the unpaired reads.  This is something that a proficient user of the workflow can easily modify if they want to
