### ISSUE TITLE
Remove 'RowID' from first row and provide real sample names

### ISSUE THREAD

**Issue by spficklin** [feltus/OSG-GEM#11]
The GEM_merged.txt file has in the first column of the first row the text 'RowID'.   This is different from what KINC expects.  It wants the first row to only contain the sample names.  

Also, would it be possible to change input1 = , input 2 = in the config file to be the sample names?  Right now the sample names look something like this:  2-merged_counts.fpkm.   But, with the new KINC that uses mixture models to identify condition-specific expression, we need the original sample names to match up the sample annotations.

**Comment by wpoehlm** [comment]
Yeah, the sample ID thing is a pain.  I will write a little script to convert the header.  Are the students' workflows starting to finish?

**Comment by spficklin** [comment]
Yes, they are!  Although OSG I think is a bit busy so it's causing some slowness but so far so good.

**Comment by wpoehlm** [comment]
@spficklin The output files from the workflow will now contain the original sample ID.  For example if your config file has the following inputs listed:

sampleA = ./sampleA_1.fastq.gz ./sampleB_2.fastq.gz
sampleB = ./sampleB_1.fastq.gz ./sampleB_2.fastq.gz 

The header of the gem will look like : 

sampleA-fpkm sampleB-fpkm

**Comment by spficklin** [comment]
That's great!  Thanks
