### ISSUE TITLE
Pegasus 4.7 in local home directory of rynge

### ISSUE THREAD

**Issue by spficklin** [feltus/OSG-GEM#3]
I'm trying to run OSG-GEM and it seems that Pegasus version 4.7 is housed in a home directory:

/home/rynge/software/pegasus-4.7.0dev/bin

Shouldn't this be a global module that can be loaded?  I suspect it's this way because Pegasus 4.7 is currently not a module on OSG.  Can a request be made for Pegasus 4.7 to be installed as a module so we don't rely on a user's home directory?

**Comment by wpoehlm** [comment]
Yeah, I'm guessing they were waiting for Pegasus 4.7 to be released, but I can submit a ticket to have the developer release installed as a module

**Comment by rynge** [comment]
4.7 will be release very soon, and then we will move it to either a system install or a OASIS module.

**Comment by wpoehlm** [comment]
I see that Pegasus 4.7 is now available as an OASIS module.

I will modify the workflow to use this instead of the files in Mats' home directory, and commit after testing

**Comment by wpoehlm** [comment]
Now using new OASIS module
