### ISSUE TITLE
Create SSH key as part of submit?

### ISSUE THREAD

**Issue by spficklin** [feltus/OSG-GEM#6]
So in my rush to get the pipeline running I completely skipped over the step for creating the SSH key (thanks Will for the correction). 

This isn't an urgent thing but would it be possible to have that created in the submit if it doesn't exist? Then it removes an extra step. Just an idea.

**Comment by wpoehlm** [comment]
I will note that this SSH key only needs to be created once, not every time that a workflow is submitted.  I will leave this open in case Mats has any opinion on this
