### ISSUE TITLE
Workflow Failing when using Login01 to submit

### ISSUE THREAD

**Issue by wpoehlm** [feltus/OSG-GEM#8]
The test workflow is failing when I submit it from the login01 node.  

error file: /local-scratch/wpoehlm/workflows/osg-gem-1476974120/workflow/osg-gem-1476974120/00/00/dax-level-2_ID0000003.err.002

-------------------Task #1 - dax-level-2 - ID0000003 - stdout-------------------

Error - input list to merge is of 0 length!

It doesn't seem to be finding the input files (located on either /local-scratch or /stash2), as the prepare-inputs log file says that 0 sequences were processed.  This doesn't seem to be an issue if the workflow is submitted from login02

I will look for more details about this

**Comment by rynge** [comment]
A tool we use during the data setup (pigz) was missing from login01. I have installed it, but still need to verify that it was the only problem. I will also add a better check in the workflow for this.
