### ISSUE TITLE
Workflow Failing

### ISSUE THREAD

**Issue by spficklin** [feltus/OSG-GEM#9]
We have several workflows that are failing.   Here is a list of some of the errors from different jobs that are occurring:

=============================sra-download_ID0000007=============================

 last state: POST_SCRIPT_FAILED
       site: condorpool
submit file: sra-download_ID0000007.sub
output file: 00/00/sra-download_ID0000007.out.002
 error file: 00/00/sra-download_ID0000007.err.002

-------------------------------Task #1 - Summary--------------------------------

site        : condorpool
hostname    : unknown
executable  : /var/lib/condor/execute/dir_2383007/glide_4uWk4t/execute/dir_2426497/pegasus.BbZBCm/sra-download
arguments   :   ERR305282   forward-3   reverse-3  
exitcode    : 3
working dir : /var/lib/condor/execute/dir_2383007/glide_4uWk4t/execute/dir_2426497/pegasus.BbZBCm

-------------Task #1 - sra-download - ID0000007 - Kickstart stderr--------------

**2016-10-20T11:23:53 fastq-dump.2.5.4 err: unsupported while parsing within network system module - failed ERR305282
# 

An error occurred during processing.
A report was generated into the file '/var/lib/condor/execute/dir_2383007/glide_4uWk4t/execute/dir_2426497/ncbi_error_report.xml'.
If the problem persists, you may consider sending the file
to 'sra@ncbi.nlm.nih.gov' for assistance.
=============================================================**

=============================sra-download_ID0000088=============================

 last state: POST_SCRIPT_FAILED
       site: condorpool
submit file: sra-download_ID0000088.sub
output file: 00/00/sra-download_ID0000088.out.002
 error file: 00/00/sra-download_ID0000088.err.002

-------------------------------Task #1 - Summary--------------------------------

site        : condorpool
hostname    : unknown
executable  : /var/lib/condor/execute/dir_207485/glide_ZTQO8b/execute/dir_1675578/pegasus.Z7UUTW/sra-download
arguments   :   ERR305333   forward-30   reverse-30  
exitcode    : 3
working dir : /var/lib/condor/execute/dir_207485/glide_ZTQO8b/execute/dir_1675578/pegasus.Z7UUTW

-------------Task #1 - sra-download - ID0000088 - Kickstart stderr--------------

**2016-10-20T11:09:50 fastq-dump.2.5.4 err: data corrupt while executing function within transform module - failed ERR305333
# 

An error occurred during processing.
A report was generated into the file '/var/lib/condor/execute/dir_207485/glide_ZTQO8b/execute/dir_1675578/ncbi_error_report.xml'.
If the problem persists, you may consider sending the file
# to 'sra@ncbi.nlm.nih.gov' for assistance.

**

=============================sra-download_ID0000001=============================

 last state: POST_SCRIPT_FAILED
       site: condorpool
submit file: sra-download_ID0000001.sub
output file: 00/00/sra-download_ID0000001.out.002
 error file: 00/00/sra-download_ID0000001.err.002

-------------------------------Task #1 - Summary--------------------------------

site        : condorpool
hostname    : unknown
executable  : /var/lib/condor/execute/dir_631301/glide_upOmlV/execute/dir_1871212/pegasus.9BLr28/sra-download
arguments   :   ERR305277   forward-1   reverse-1  
exitcode    : 3
working dir : /var/lib/condor/execute/dir_631301/glide_upOmlV/execute/dir_1871212/pegasus.9BLr28

-------------Task #1 - sra-download - ID0000001 - Kickstart stderr--------------

**2016-10-20T11:10:53 fastq-dump.2.5.4 err: timeout exhausted while reading file within network system module - log failure: RC(rcText,rcString,rcConverting,rcBuffer,rcInsufficient) in 'error with http open '$(U)''
2016-10-20T11:10:53 fastq-dump.2.5.4 err: item not found while constructing within virtual database module - the path 'ERR305277' cannot be opened as database or table**

=============================sra-download_ID0000043=============================

 last state: POST_SCRIPT_FAILED
       site: condorpool
submit file: sra-download_ID0000043.sub
output file: 00/00/sra-download_ID0000043.out.002
 error file: 00/00/sra-download_ID0000043.err.002

-------------------------------Task #1 - Summary--------------------------------

site        : condorpool
hostname    : unknown
executable  : /var/lib/condor/execute/dir_312607/glide_RRlwdT/execute/dir_2076081/pegasus.fWPXU2/sra-download
arguments   :   ERR588641   forward-15   reverse-15  
exitcode    : 1
working dir : /var/lib/condor/execute/dir_312607/glide_RRlwdT/execute/dir_2076081/pegasus.fWPXU2

------------------Task #1 - sra-download - ID0000043 - stdout-------------------

Read 20000000 spots for ERR588641
Written 20000000 spots for ERR588641

-------------Task #1 - sra-download - ID0000043 - Kickstart stderr--------------

**mv: cannot stat `ERR588641_2.fastq.gz': No such file or directory**

=============================sra-download_ID0000082=============================

 last state: POST_SCRIPT_FAILED
       site: condorpool
submit file: sra-download_ID0000082.sub
output file: 00/00/sra-download_ID0000082.out.002
 error file: 00/00/sra-download_ID0000082.err.002

-------------------------------Task #1 - Summary--------------------------------

site        : condorpool
hostname    : unknown
executable  : /var/lib/condor/execute/dir_3898669/glide_5YJI48/execute/dir_3663218/pegasus.ZjhKHv/sra-download
arguments   :   SRR2931457   forward-28   reverse-28  
exitcode    : 127
working dir : /var/lib/condor/execute/dir_3898669/glide_5YJI48/execute/dir_3663218/pegasus.ZjhKHv

-------------Task #1 - sra-download - ID0000082 - Kickstart stderr--------------

**./sra-download: line 3: /cvmfs/oasis.opensciencegrid.org/osg/sw/module-init.sh: Input/output error
./sra-download: line 14: fastq-dump: command not found**

=============================sra-download_ID0000100=============================

 last state: POST_SCRIPT_FAILED
       site: condorpool
submit file: sra-download_ID0000100.sub
output file: 00/00/sra-download_ID0000100.out.002
 error file: 00/00/sra-download_ID0000100.err.002

-------------------------------Task #1 - Summary--------------------------------

site        : condorpool
hostname    : unknown
executable  : /var/lib/condor/execute/dir_398917/glide_s49U0e/execute/dir_3655668/pegasus.rGg14R/sra-download
arguments   :   SRR1185246   forward-34   reverse-34
exitcode    : 3
working dir : /var/lib/condor/execute/dir_398917/glide_s49U0e/execute/dir_3655668/pegasus.rGg14R

------------------Task #1 - sra-download - ID0000100 - stdout-------------------

Rejected 14750720 READS because READLEN < 1

-------------Task #1 - sra-download - ID0000100 - Kickstart stderr--------------

**2016-10-19T12:00:35 fastq-dump.2.5.4 err: data corrupt while executing function within transform module - failed SRR1185246
# 

An error occurred during processing.
A report was generated into the file '/var/lib/condor/execute/dir_398917/glide_s49U0e/execute/dir_3655668/ncbi_error_report.xml'.
If the problem persists, you may consider sending the file
to 'sra@ncbi.nlm.nih.gov' for assistance.
=============================================================**

=============================sra-download_ID0000100=============================

 last state: POST_SCRIPT_FAILED
       site: condorpool
submit file: sra-download_ID0000100.sub
output file: 00/00/sra-download_ID0000100.out.002
 error file: 00/00/sra-download_ID0000100.err.002

-------------------------------Task #1 - Summary--------------------------------

site        : condorpool
hostname    : unknown
executable  : /var/lib/condor/execute/dir_398917/glide_s49U0e/execute/dir_3655668/pegasus.rGg14R/sra-download
arguments   :   SRR1185246   forward-34   reverse-34
exitcode    : 3
working dir : /var/lib/condor/execute/dir_398917/glide_s49U0e/execute/dir_3655668/pegasus.rGg14R

------------------Task #1 - sra-download - ID0000100 - stdout-------------------

Rejected 14750720 READS because READLEN < 1

-------------Task #1 - sra-download - ID0000100 - Kickstart stderr--------------

**2016-10-19T12:00:35 fastq-dump.2.5.4 err: data corrupt while executing function within transform module - failed SRR1185246
# 

An error occurred during processing.
A report was generated into the file '/var/lib/condor/execute/dir_398917/glide_s49U0e/execute/dir_3655668/ncbi_error_report.xml'.
If the problem persists, you may consider sending the file
to 'sra@ncbi.nlm.nih.gov' for assistance.
=============================================================**

**Comment by wpoehlm** [comment]
This issue partly seems to be the result of trying to download single-end read datasets.  OSG-GEM will only work for paired-end reads.  

I think that it would be a helpful if we modify the workflow to allow it to proceed in the presence of failed SRA download jobs.

**Comment by spficklin** [comment]
Oh. I was not aware of this.  :-(  Now that I look at the OSG-GEM paper it clearly states in the abstract it works for paired-end data but it didn't register in my brain that it was only paired-end.  

Any chance non-paired data can be supported as a quick fix?

**Comment by spficklin** [comment]
It seems on one of my test jobs the jobs are failing because of timeouts:

> 000 (2398862.000.000) 10/23 07:40:29 Job submitted from host: <192.170.227.192:33279?addrs=192.170.227.192-33279>
> 001 (2398862.000.000) 10/23 07:43:22 Job executing on host: <10.128.11.35:48972?CCBID=129.79.53.179:9878%3faddrs%3d129.79.53.179-9878#1323577&addrs=10.128.11.35-48972&noUDP>
> 006 (2398862.000.000) 10/23 07:43:32 Image size of job updated: 3
> 022 (2398862.000.000) 10/23 07:44:57 Job disconnected, attempting to reconnect
> 023 (2398862.000.000) 10/23 07:45:22 Job reconnected to glidein_36015_587462512@c8-16.icecube.wisc.edu
> 022 (2398862.000.000) 10/23 07:49:23 Job disconnected, attempting to reconnect
> 023 (2398862.000.000) 10/23 07:49:50 Job reconnected to glidein_36015_587462512@c8-16.icecube.wisc.edu
> 022 (2398862.000.000) 10/23 07:56:14 Job disconnected, attempting to reconnect
> 023 (2398862.000.000) 10/23 07:57:09 Job reconnected to glidein_36015_587462512@c8-16.icecube.wisc.edu
> 022 (2398862.000.000) 10/23 08:06:24 Job disconnected, attempting to reconnect
> 023 (2398862.000.000) 10/23 08:06:43 Job reconnected to glidein_36015_587462512@c8-16.icecube.wisc.edu
> 022 (2398862.000.000) 10/23 08:25:43 Job disconnected, attempting to reconnect
> 023 (2398862.000.000) 10/23 08:26:04 Job reconnected to glidein_36015_587462512@c8-16.icecube.wisc.edu
> 022 (2398862.000.000) 10/23 09:01:59 Job disconnected, attempting to reconnect
> 024 (2398862.000.000) 10/23 09:06:04 Job reconnection failed
> 001 (2398862.000.000) 10/23 10:12:35 Job executing on host: <10.128.11.44:42068?CCBID=129.79.53.179:9759%3faddrs%3d129.79.53.179-9759#1300491&addrs=10.128.11.44-42068&noUDP>
> 006 (2398862.000.000) 10/23 10:12:44 Image size of job updated: 3
> 022 (2398862.000.000) 10/23 10:13:26 Job disconnected, attempting to reconnect
> 023 (2398862.000.000) 10/23 10:13:30 Job reconnected to glidein_7957_93346560@c9-5.icecube.wisc.edu
> 022 (2398862.000.000) 10/23 10:16:44 Job disconnected, attempting to reconnect
> 023 (2398862.000.000) 10/23 10:16:49 Job reconnected to glidein_7957_93346560@c9-5.icecube.wisc.edu
> 006 (2398862.000.000) 10/23 10:17:44 Image size of job updated: 140316
> 022 (2398862.000.000) 10/23 10:19:00 Job disconnected, attempting to reconnect
> 023 (2398862.000.000) 10/23 10:19:06 Job reconnected to glidein_7957_93346560@c9-5.icecube.wisc.edu
> 009 (2398862.000.000) 10/23 10:20:33 Job was aborted by the user.

When it switches to a new node in the log above, it's because there was no response for over 40 minutes! So it gave up and rescheduled on a new node.

**Comment by wpoehlm** [comment]
Was the above test job using login02?  It looks like there might be an issue with it's communication with the job scheduler node right now, I submitted a support ticket last night.  

As for adding support for single end reads, it's certainly possible but I honestly don't think that we can do this quickly.  With Pegasus and Condor, the input and output filenames have to be catalogued in the dax xml files that are created by the workflow.  The filenames in OSG-GEM are designed to accommodate paired reads, so adding support single end reads would require a pretty big overhaul.  We would need to create new job wrappers for the SRA download, prepare-inputs, and hisat2 jobs, and figure out how to specify which datasets are single vs. paired in the config file in a way that allows a mixture of both read types to be processed

**Comment by wpoehlm** [comment]
I've added a new branch "Single" that offers initial support for single end reads (But not a mixture of single and paired reads).  This needs testing on full datasets
